/*
	Suppose the College Admin wants to see a list of Students 
	with the Courses enrolled & the amount of fees paid
*/
	
CREATE PROCEDURE sp_getStudentData
AS
	BEGIN
		SELECT CONCAT( s_firstName, ' ',  s_lastName) AS studentName, 
		c_name AS courseName, s_fees AS feesPaid 
		FROM Student INNER JOIN Courses ON Student.c_id = Courses.c_id 
		ORDER BY courseName
	END

EXEC sp_getStudentData;

/*
	Suppose the College Administration wants to see revenue generated by each Course
*/


CREATE PROCEDURE sp_getCourseIdWiseRevenue
AS
	BEGIN
		SELECT c_id AS courseID, SUM(s_fees) AS courseRevenue 
		FROM Student 
		GROUP BY c_id ORDER BY SUM(s_fees) DESC;
	END

EXEC sp_getCourseIdWiseRevenue;