/*
	By Using CTE's I found out the Revenue generated by All Films and Films with Certain Keywords like 'SQL' or 'Tech' in the description
	The Total Revenue Generated is 61312.04 and the Revenue Generated by using Techie Keywords is 20998.01 which is 1/3rd of the total Revenue
	So I think implementing a NLP Model For Targeted Marketing by using certain keywords would definitely be useful to catch & retain Customers
*/

WITH total_revenue AS (
SELECT 
	f.title AS filmTitle, 
	SUM(amount) AS sumRentalAmt
FROM 
	payment pay,rental rent,inventory inv,film f 
WHERE 
	pay.rental_id = rent.rental_id AND
	rent.inventory_id = inv.inventory_id AND
	inv.film_id = f.film_id
GROUP BY 
	filmTitle
ORDER BY 
	sumRentalAmt DESC
)

SELECT SUM(sumRentalAmt) AS sumTotal from total_revenue;

-- Total Revenue = 61312.04

with tech_revenue AS (
SELECT 
	title,
	SUM(amount) as sumAmount,
	COUNT(rental_duration) as cntRentalDuration
FROM 
	film
JOIN 
	inventory ON FILM.film_id = inventory.film_id
JOIN 
	rental ON inventory.inventory_id = rental.inventory_id
JOIN 
	payment ON rental.rental_id = payment.rental_id
WHERE 
	FILM.film_id IN (
	SELECT 
		film_id FROM Film 
	WHERE 
	description like '%Database%' OR description like '%SQL%' OR 
	description like '%Tech%' OR description like '%Robot%' OR
	description like '%Scientist%'
)
GROUP BY FILM.film_id
ORDER BY sumAmount DESC, cntRentalDuration DESC
)

SELECT SUM(sumAmount) AS sumTech from tech_revenue;

-- Tech Revenue = 20998.01
